name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun coverage
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
