name: All Tests

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install && npx playwright install --with-deps
      - name: Run tests
        run: npm run test && npm run test-e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.environment_url }}
