name: All Tests

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  deployment_status:
  workflow_dispatch:

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install && bun playwright install --with-deps
      - name: Run tests
        run: bun run test && bun run test:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.environment_url }}
